# -*- coding: utf-8 -*-
"""ML3_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LGOxipsuJuQFoiL7SFJeIJ1CFrWF9JHC
"""

!pip install shap scikit-learn pandas numpy matplotlib

# --Imports and Global Settings--

# Import libraries for data handling
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import shap # for explaining model decisions
import warnings
import csv

# Ignoring warnings for clean output
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

# Import ml tools from sklearn
from sklearn.datasets import load_diabetes
from sklearn.model_selection import KFold, RandomizedSearchCV
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, max_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
from sklearn.svm import SVR

# Fixed random seed (6)
SEED = 42
np.random.seed(SEED)

# --Data Loading and Analysis--

# Load the diabetes dataset (1)
diabetes_data = load_diabetes(as_frame=True, scaled=False) # scaled=False for raw numbers
df = diabetes_data.frame

# Print the range of specific columns (2)
print(f"Range of 'age': {df['age'].min()} - {df['age'].max()}")
print(f"Range of 'bmi': {df['bmi'].min()} - {df['bmi'].max()}")

# Check for missing values (NaN) and removal (3)
if df.isnull().values.any():
  print("Found NaN entries, deleting...")
  df = df.dropna()
else:
  print("No NaN entries found.")

X = df.drop(columns='target').values
y = df['target'].values

# Histogram to visualize the target column (4)
plt.figure(figsize=(10, 6), dpi=100)
plt.hist(y, bins=30, color='skyblue', edgecolor='black')
plt.title('Distribution of Target Variable (Disease Progression)', fontsize=14)
plt.xlabel('Measure', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.grid(axis='y', alpha=0.5)
plt.show()

# --Data Normalization-- (5)

# Initialize Scalers
scaler_X = MinMaxScaler() # all numbers into range between 0 and 1
scaler_y = MinMaxScaler()

# Apply to the data
X_scaled = scaler_X.fit_transform(X)
y_scaled = scaler_y.fit_transform(y.reshape(-1, 1)).flatten()

# --Helper Functions--

# MAPE function
def calculate_mape(y_true, y_pred):
  # Into numpy array
  y_true, y_pred = np.array(y_true), np.array(y_pred)

  #Avoid crashing divition by zero
  epsilon = 1e-10

  # Type: Mean(|(Actual - Pred) / Actual|) * 100
  return np.mean(np.abs((y_true - y_pred) / (y_true + epsilon))) * 100

# All metrics used
def get_metrics(act, pred):
    rmse = np.sqrt(mean_squared_error(act, pred))
    mae = mean_absolute_error(act, pred)
    mx = max_error(act, pred)
    mape = calculate_mape(act, pred)
    return [mx, rmse, mae, mape]

# Random Forest function
def train_random_forest(X_train, y_train, seed):

  # Base model
  rf = RandomForestRegressor(random_state=seed)

  # Settings to test
  param_dist = {
      'n_estimators': [50, 100, 200], # trees
      'max_depth': [None, 10, 20, 30], # max depth of trees
      'min_samples_split': [2, 5, 10], # min samples to split a node
      'min_samples_leaf': [1, 2, 4] # min samples in a leaf
  }

  # Tries different combinations to find the best one
  search = RandomizedSearchCV(
      estimator=rf,
      param_distributions=param_dist,
      n_iter=10, # 10 random combinations
      cv=3, # Cross-validation splits
      random_state=seed,
      n_jobs=-1 # All cpu cores usage
  )

  # Train the model
  search.fit(X_train, y_train.ravel())
  print(f"Best Params: {search.best_params_}")
  return search.best_estimator_

# KNN Training Function
def train_knn(X_train, y_train, seed):
  """Trains a KNN model using Randomized Search."""
  knn = KNeighborsRegressor()
  param_dist = {
    'n_neighbors': range(1, 31),
    'weights': ['uniform', 'distance'],
    'p': [1, 2]
  }
  search = RandomizedSearchCV(knn, param_dist, n_iter=15, cv=3, random_state=seed, n_jobs=-1)
  search.fit(X_train, y_train.ravel())
  print(f"Best KNN Params: {search.best_params_}")
  return search.best_estimator_

# Gaussian Process Function
def train_gaussian_process(X_train, y_train, seed):
  """Trains a Gaussian Process Regressor using Randomized Search."""

  # Define the Kernel
  # Constant Kernel combined with RBF (Radial Basis Function)
  kernel = C(1.0, (1e-3, 1e3)) * RBF(10, (1e-2, 1e2))

  # Define the Model
  gpr = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=2, random_state=seed)

  # Settings to test (Alpha controls noise level)
  param_dist = {
    'alpha': [1e-2, 0.1, 1.0]
  }

  # Randomized Search
  search = RandomizedSearchCV(
    estimator=gpr,
    param_distributions=param_dist,
    n_iter=5, # keep iterations low
    cv=3,
    random_state=seed,
    n_jobs=-1
  )

  search.fit(X_train, y_train.ravel())
  print(f"Best GPR Params: {search.best_params_}")
  return search.best_estimator_

# SVR Function
def train_svr(X_train, y_train, seed):
  """Trains a Support Vector Regressor using Randomized Search."""

  # Define the Model
  svr = SVR()

  # Settings to test
  param_dist = {
    'C': [0.1, 1, 10],            # Regularization parameter
    'kernel': ["linear", "rbf"],  # Kernel type
    'epsilon': [0.01, 0.1]        # Margin of tolerance
  }

  # Randomized Search
  search = RandomizedSearchCV(
    estimator=svr,
    param_distributions=param_dist,
    n_iter=5,  # iterations low for speed
    cv=3,
    random_state=seed,
    n_jobs=-1
  )

  search.fit(X_train, y_train.ravel())
  print(f"Best SVR Params: {search.best_params_}")
  return search.best_estimator_

# --Results Setup--

# List to store results (8)
csv_data = []
csv_header = ["Model", "Set", "Fold", "Max_n", "RMSE_n", "MAE_n", "MAPE_n",
              "Max", "RMSE", "MAE", "MAPE"]
csv_data.append(csv_header)

# Setup K-Fold Cross Validation (7)
kf = KFold(n_splits=6, shuffle=True, random_state=SEED)
print("Setup is ready. Starting the loop...")

# --Main Loop-- (9)

# 6 folds loop
for fold, (train_index, test_index) in enumerate(kf.split(X_scaled, y_scaled)):

  # Splitting data into Train and Test for each fold
  X_train, X_test = X_scaled[train_index], X_scaled[test_index]
  y_train, y_test = y_scaled[train_index], y_scaled[test_index]

  print(f"Fold {fold}: Train shape {X_train.shape}, Test shape {X_test.shape}")
  print("-" * 50)


  # Part 1: Random Forest
  print(f"--> Training Random Forest (Fold {fold})")

  # Train the model
  rf_model = train_random_forest(X_train, y_train, SEED)

  # Normalized predictions
  pred_train_n = rf_model.predict(X_train)
  pred_test_n = rf_model.predict(X_test)

  # Denormalize
  pred_train = scaler_y.inverse_transform(pred_train_n.reshape(-1, 1)).flatten()
  pred_test = scaler_y.inverse_transform(pred_test_n.reshape(-1, 1)).flatten()
  y_train_real = scaler_y.inverse_transform(y_train.reshape(-1, 1)).flatten()
  y_test_real = scaler_y.inverse_transform(y_test.reshape(-1, 1)).flatten()


  # Calculate metrics
  metrics_train = get_metrics(y_train_real, pred_train)
  metrics_test = get_metrics(y_test_real, pred_test)
  metrics_train_n = get_metrics(y_train, pred_train_n)
  metrics_test_n = get_metrics(y_test, pred_test_n)

  print(f"RF Test RMSE: {metrics_test[1]:.2f}, MAPE: {metrics_test[3]:.2f}%")

  # Save to CSV List
  csv_data.append(["Random Forest", "Train", fold] + metrics_train_n + metrics_train)
  csv_data.append(["Random Forest", "Test", fold] + metrics_test_n + metrics_test)

  # Visualizations
  plt.figure(figsize=(8, 8), dpi=100)
  plt.scatter(y_test_real, pred_test, alpha=0.6, color='green', s=60)
  plt.plot([y_test_real.min(), y_test_real.max()], [y_test_real.min(), y_test_real.max()], 'r--', lw=2)
  plt.title(f'Random Forest - Fold {fold}: Actual vs Predicted', fontsize=14)
  plt.xlabel('Actual (mg/dL)', fontsize=12)
  plt.ylabel('Predicted (mg/dL)', fontsize=12)
  plt.grid(True, alpha=0.3)
  plt.show()
  plt.close()

  print("\n" * 2)

  # SHAP
  print("Generating SHAP for Random Forest...")

  try:
    # TreeExplainer
    explainer = shap.TreeExplainer(rf_model)
    shap_values = explainer.shap_values(X_test)

    if isinstance(shap_values, list):
      shap_values = shap_values[0]

    # Summary Plot
    plt.figure(figsize=(12, 8))
    plt.title(f"SHAP Summary (Random Forest) - Fold {fold}", fontsize=14)
    shap.summary_plot(shap_values, X_test, feature_names=diabetes_data.feature_names, show=False)
    plt.tight_layout()
    plt.show()
    plt.close()

    # Waterfall Plots
    base_value = explainer.expected_value
    if isinstance(base_value, (list, np.ndarray)):
      if len(base_value) == 1: base_value = base_value[0]
      elif isinstance(shap_values, list): base_value = base_value[0] # Fallback

    exp = shap.Explanation(
      shap_values,
      base_value,
      data=X_test,
      feature_names=diabetes_data.feature_names
    )

    for i in [0, 1]:
      if i < len(X_test):
        plt.figure()
        shap.plots.waterfall(exp[i], show=False)
        plt.gcf().set_size_inches(14, 7)
        plt.title(f"SHAP Waterfall (Random Forest) - Sample {i} (Fold {fold})", fontsize=14)
        plt.tight_layout()
        plt.show()
        plt.close()

    print("Random Forest Completed.\n")

  except Exception as e:
    print(f"SHAP Error (RF): {e}")


  # Part 2: Gaussian Process
  print(f"--> Training Gaussian Process (Fold {fold})")

  # Train the model
  gpr_model = train_gaussian_process(X_train, y_train, SEED)

  # Normalized predictions
  pred_train_n = gpr_model.predict(X_train)
  pred_test_n = gpr_model.predict(X_test)

  # Denormalize
  pred_train = scaler_y.inverse_transform(pred_train_n.reshape(-1, 1)).flatten()
  pred_test = scaler_y.inverse_transform(pred_test_n.reshape(-1, 1)).flatten()
  y_train_real = scaler_y.inverse_transform(y_train.reshape(-1, 1)).flatten()
  y_test_real = scaler_y.inverse_transform(y_test.reshape(-1, 1)).flatten()

  # Calculate Metrics
  metrics_train = get_metrics(y_train_real, pred_train)
  metrics_test = get_metrics(y_test_real, pred_test)
  metrics_train_n = get_metrics(y_train, pred_train_n)
  metrics_test_n = get_metrics(y_test, pred_test_n)

  print(f"GPR Test RMSE: {metrics_test[1]:.2f}, MAPE: {metrics_test[3]:.2f}%")

  # Save to CSV List
  csv_data.append(["Gaussian Process", "Train", fold] + metrics_train_n + metrics_train)
  csv_data.append(["Gaussian Process", "Test", fold] + metrics_test_n + metrics_test)

  # Visualizations
  plt.figure(figsize=(8, 8), dpi=100)
  plt.scatter(y_test_real, pred_test, alpha=0.6, color='purple', s=60)
  plt.plot([y_test_real.min(), y_test_real.max()], [y_test_real.min(), y_test_real.max()], 'r--', lw=2)
  plt.title(f'Gaussian Process - Fold {fold}: Actual vs Predicted', fontsize=14)
  plt.xlabel('Actual (mg/dL)', fontsize=12)
  plt.ylabel('Predicted (mg/dL)', fontsize=12)
  plt.grid(True, alpha=0.3)
  plt.show()
  plt.close()

  print("\n" * 2)

  # SHAP
  print("Generating SHAP for Gaussian Process...")
  try:
    # KernelExplainer
    background = shap.kmeans(X_train, 10)
    explainer = shap.KernelExplainer(gpr_model.predict, background)
    shap_values = explainer.shap_values(X_test)

    if isinstance(shap_values, list):
      shap_values = shap_values[0]

    # Summary Plot
    plt.figure(figsize=(12, 8))
    plt.title(f"SHAP Summary (GPR) - Fold {fold}", fontsize=14)
    shap.summary_plot(shap_values, X_test, feature_names=diabetes_data.feature_names, show=False)
    plt.tight_layout()
    plt.show()
    plt.close()

    # Waterfall Plots
    base_value = explainer.expected_value
    if isinstance(base_value, (list, np.ndarray)):
      if len(base_value) == 1: base_value = base_value[0]

    exp = shap.Explanation(
      shap_values,
      base_value,
      data=X_test,
      feature_names=diabetes_data.feature_names
    )

    for i in [0, 1]:
      if i < len(X_test):
        plt.figure()
        shap.plots.waterfall(exp[i], show=False)
        plt.gcf().set_size_inches(14, 7)
        plt.title(f"SHAP Waterfall (GPR) - Sample {i} (Fold {fold})", fontsize=14)
        plt.tight_layout()
        plt.show()
        plt.close()

    print("Gaussian Process Completed.\n")

  except Exception as e:
    print(f"SHAP Error (GPR): {e}")

  # Part 3: SVR
  print(f"--> Training SVR (Fold {fold})")

  # Train the model
  svr_model = train_svr(X_train, y_train, SEED)

  # Normalized predictions
  pred_train_n = svr_model.predict(X_train)
  pred_test_n = svr_model.predict(X_test)

  # Denormalize
  pred_train = scaler_y.inverse_transform(pred_train_n.reshape(-1, 1)).flatten()
  pred_test = scaler_y.inverse_transform(pred_test_n.reshape(-1, 1)).flatten()
  y_train_real = scaler_y.inverse_transform(y_train.reshape(-1, 1)).flatten()
  y_test_real = scaler_y.inverse_transform(y_test.reshape(-1, 1)).flatten()

  # Calculate Metrics
  metrics_train = get_metrics(y_train_real, pred_train)
  metrics_test = get_metrics(y_test_real, pred_test)
  metrics_train_n = get_metrics(y_train, pred_train_n)
  metrics_test_n = get_metrics(y_test, pred_test_n)

  print(f"SVR Test RMSE: {metrics_test[1]:.2f}, MAPE: {metrics_test[3]:.2f}%")

  # Save to CSV List
  csv_data.append(["SVR", "Train", fold] + metrics_train_n + metrics_train)
  csv_data.append(["SVR", "Test", fold] + metrics_test_n + metrics_test)

  # Visualizations
  plt.figure(figsize=(8, 8), dpi=100)
  plt.scatter(y_test_real, pred_test, alpha=0.6, color='crimson', s=60)
  plt.plot([y_test_real.min(), y_test_real.max()], [y_test_real.min(), y_test_real.max()], 'r--', lw=2)
  plt.title(f'SVR - Fold {fold}: Actual vs Predicted', fontsize=14)
  plt.xlabel('Actual (mg/dL)', fontsize=12)
  plt.ylabel('Predicted (mg/dL)', fontsize=12)
  plt.grid(True, alpha=0.3)
  plt.show()
  plt.close()

  print("\n" * 2)

  # SHAP
  print("Generating SHAP for SVR...")
  try:
    # KernelExplainer
    background = shap.kmeans(X_train, 10)
    explainer = shap.KernelExplainer(svr_model.predict, background)
    shap_values = explainer.shap_values(X_test)

    if isinstance(shap_values, list):
      shap_values = shap_values[0]

    # Summary Plot
    plt.figure(figsize=(12, 8))
    plt.title(f"SHAP Summary (SVR) - Fold {fold}", fontsize=14)
    shap.summary_plot(shap_values, X_test, feature_names=diabetes_data.feature_names, show=False)
    plt.tight_layout()
    plt.show()
    plt.close()

    # Waterfall Plots
    base_value = explainer.expected_value
    if isinstance(base_value, (list, np.ndarray)):
      if len(base_value) == 1: base_value = base_value[0]

    exp = shap.Explanation(
      shap_values,
      base_value,
      data=X_test,
      feature_names=diabetes_data.feature_names
    )

    for i in [0, 1]:
      if i < len(X_test):
        plt.figure()
        shap.plots.waterfall(exp[i], show=False)
        plt.gcf().set_size_inches(14, 7)
        plt.title(f"SHAP Waterfall (SVR) - Sample {i} (Fold {fold})", fontsize=14)
        plt.tight_layout()
        plt.show()
        plt.close()

    print("SVR Completed.\n")

  except Exception as e:
    print(f"SHAP Error (SVR): {e}")

  # Part 4: KNN
  print(f"--> Training KNN (Fold {fold})")

  # Train the model
  knn_model = train_knn(X_train, y_train, SEED)

  # Normalized predictions
  pred_train_n = knn_model.predict(X_train)
  pred_test_n = knn_model.predict(X_test)

  # Denormalize
  pred_train = scaler_y.inverse_transform(pred_train_n.reshape(-1, 1)).flatten()
  pred_test = scaler_y.inverse_transform(pred_test_n.reshape(-1, 1)).flatten()
  y_train_real = scaler_y.inverse_transform(y_train.reshape(-1, 1)).flatten()
  y_test_real = scaler_y.inverse_transform(y_test.reshape(-1, 1)).flatten()

  # Calculate Metrics
  metrics_train = get_metrics(y_train_real, pred_train)
  metrics_test = get_metrics(y_test_real, pred_test)
  metrics_train_n = get_metrics(y_train, pred_train_n)
  metrics_test_n = get_metrics(y_test, pred_test_n)

  print(f"KNN Test RMSE: {metrics_test[1]:.2f}, MAPE: {metrics_test[3]:.2f}%")

  # Save to CSV List
  csv_data.append(["KNN", "Train", fold] + metrics_train_n + metrics_train)
  csv_data.append(["KNN", "Test", fold] + metrics_test_n + metrics_test)

  # Visualizations
  plt.figure(figsize=(8, 8), dpi=100)
  plt.scatter(y_test_real, pred_test, alpha=0.6, color='darkorange', s=60)
  plt.plot([y_test_real.min(), y_test_real.max()], [y_test_real.min(), y_test_real.max()], 'r--', lw=2)
  plt.title(f'KNN - Fold {fold}: Actual vs Predicted', fontsize=14)
  plt.xlabel('Actual (mg/dL)', fontsize=12)
  plt.ylabel('Predicted (mg/dL)', fontsize=12)
  plt.grid(True, alpha=0.3)
  plt.show()
  plt.close()

  print("\n" * 2)

  # SHAP
  print("Generating SHAP for KNN...")
  try:
    # KernelExplainer
    background = shap.kmeans(X_train, 10)
    explainer = shap.KernelExplainer(knn_model.predict, background)
    shap_values = explainer.shap_values(X_test)

    if isinstance(shap_values, list):
      shap_values = shap_values[0]

    # Summary Plot
    plt.figure(figsize=(12, 8))
    plt.title(f"SHAP Summary (KNN) - Fold {fold}", fontsize=14)
    shap.summary_plot(shap_values, X_test, feature_names=diabetes_data.feature_names, show=False)
    plt.tight_layout()
    plt.show()
    plt.close()

    # Waterfall Plots
    base_value = explainer.expected_value
    if isinstance(base_value, (list, np.ndarray)):
      if len(base_value) == 1: base_value = base_value[0]

    exp = shap.Explanation(
      shap_values,
      base_value,
      data=X_test,
      feature_names=diabetes_data.feature_names
    )

    for i in [0, 1]:
      if i < len(X_test):
        plt.figure()
        shap.plots.waterfall(exp[i], show=False)
        plt.gcf().set_size_inches(14, 7)
        plt.title(f"SHAP Waterfall (KNN) - Sample {i} (Fold {fold})", fontsize=14)
        plt.tight_layout()
        plt.show()
        plt.close()

    print("KNN Completed.\n")

  except Exception as e:
    print(f"SHAP Error (KNN): {e}")


  print("\n")
  print(f"End of Fold {fold}")
  print("-" * 100)
  print("\n")

with open('regression_results.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(csv_data)
print("All models finished. Results saved to 'regression_results.csv'.")